apiVersion: v1
kind: PersistentVolume
metadata:
    name: rabbitmq-data
    labels:
      release: rabbitmq-data
spec:
    capacity:
      storage: 60Gi
    accessModes:
      - ReadWriteMany
    persistentVolumeReclaimPolicy: Delete
    nfs:
      path: /rabbit #这个文件夹要提前在nfs下面创建好
      server: nfs地址
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-data-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:  
    requests:
      storage: 60Gi
  selector:
    matchLabels:
      release: rabbitmq-data
